### ISSUE TITLE
Optionally, change special characters to normal characters.

### ISSUE THREAD

**Issue by aitormendez** [sogoagain/scrambling-text-js#1]
Hi, could I ask for a feature request?

Adding an option to use normal alphabet characters for substitution instead of special characters. Something like:

`this.normalCharacters = ['a', 'b, 'c', 'd, 'e', 'f', … ];`

https://github.com/sogoagain/scrambling-text-js/blob/master/src/Scrambler.js#L3

Thank you.

**Comment by sogoagain** [comment]
@aitormendez
Thanks for using 'scrambling-text-js'.
I will add the options you requested as soon as possible.
Have a nice day!

**Comment by sogoagain** [comment]
@aitormendez 
Hello! The 1.1.0 version contains related features.
Sorry to keep you waiting so long.

Please refer to the code below.

```javascript
// call scramble with the option to set the characters to use when scrambled.
scrambler.scramble(text, handleScramble, {
  charactersToUseWhenScrambling: ['a', 'b', 'c'],
});

// Scrambler provides several characters.
console.log(Scrambler.CHARACTERS.DEFAULT);
console.log(Scrambler.CHARACTERS.ALPHABET);
```

thank you!
