### ISSUE TITLE
Manually Stop it from scrambing

### ISSUE THREAD

**Issue by Cholowao** [sogoagain/scrambling-text-js#9]
I am fetching data from the server, can it scramble and then stop only after the data was loaded from the server.

**Comment by sogoagain** [comment]
Hello, @Cholowao 

If you want to scramble the text while waiting for the server's response, you can try the following method, although it's not a perfect solution. The `scramble()` function continues to run with arbitrary text as input until a response is received from the server. When the server responds, the `scramble()` function is finally called with the response value as input.

Here is an example code: 

![scrambling-text-js-continuously-until-certain-timing](https://user-images.githubusercontent.com/23417465/206194461-214ce711-37cf-450c-bb82-45a8be9d848e.gif)

- [codesandbox - scrambling-text-js-continuously-until-certain-timing](https://codesandbox.io/s/scrambling-text-js-continuously-until-certain-timing-3q04zm)

Here's how it works:

1. Assume that the server response is received after 10 seconds.
2. While waiting for the server response, the `scramble()` function is called every 2 seconds to scramble random text.
3. When a response is received from the server, the `scramble()` function is called one last time with the corresponding response value and then terminated.

Note that this is just one solution. There may be other ways to solve the problem. If you would like to add a feature to scrambling-text, please let me know the specifications of the feature you are thinking of. Alternatively, you can contribute by developing the new feature yourself and creating a pull request (PR).

I hope this helps.
Thank you.

**Comment by Cholowao** [comment]
This does the job, thanks!
